version: '3'

services:
    api:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        command: bash -c "node main.js"
        volumes:
            - ./backend/:/code
        ports:
            - "8000:8000"
